kind: Deployment
apiVersion: apps/v1
metadata:
  name: assistant-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assistant-proxy
  template:
    metadata:
      labels:
        app: assistant-proxy
    spec:
      containers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: assistant-proxy
          env:
            - name: LLAMA_STACK_URL
              value: http://llamastack.llamastack.svc.cluster.local:8321
          ports:
            - containerPort: 8321
              protocol: TCP
          imagePullPolicy: Always
          terminationMessagePolicy: File
          image: 'quay.io/gnunn/assistant-proxy:latest'
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
