apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: assistant-proxy
spec:
  host: argocd-server-demo-gitops.apps.home.ocplab.com
  path: /assistant
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: assistant-proxy
    weight: 100
  wildcardPolicy: None
